### ISSUE TITLE
Install as `gds` instead of `gds-cli`

### ISSUE THREAD

**Issue by AP-Hunt** [alphagov/homebrew-gds#6]
The previous makefile target installed this as `gds` not `gds-cli`. It would be nice if brew could do the same thing as well/instead of.

**Comment by issyl0** [comment]
PRs accepted. :wink: Looks like `bin.install "gds-cli" => "gds"` should do it. Also PRs welcome to change all the docs back to `gds` :wink:

**Comment by AP-Hunt** [comment]
Shall raise a PR :D

**Comment by issyl0** [comment]
You can edit your local version of the formula (for testing purposes) with `brew edit gds-cli`.

**Comment by AP-Hunt** [comment]
> You can edit your local version of the formula (for testing purposes) with `brew edit gds-cli`.

That is incredibly helpful, thanks!
